services:
  - type: web
    name: crewai-api
    env: docker
    repo: https://github.com/jayusctrojan/crewai.git
    healthCheckPath: /health
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: API_KEY
        sync: false
      - key: PORT
        value: 8000